[package]
name = "zkp"
version = "0.1.0"
authors = ["sun"]
edition = "2018"

[workspace]
members = [
    "math",
    "curve",
    "scheme"
]

[features]
default = ["full"]
full = ["parallel", "bn_256", "bls12_381", "groth16", "bolletproofs"]
parallel = ["std", "math/parallel", "curve/parallel", "scheme/parallel"]
std = ["math/std", "curve/std", "scheme/std"]
bn_256 = ["curve/bn_256"]
bls12_381 = ["curve/bls12_381"]
#groth16 = ["scheme/groth16"]
groth16 = []
bolletproofs = []

[dependencies]
math = { path = "math", default-features = false }
scheme = { path = "scheme", default-features = false }
curve = { path = "curve", default-features = false }

[dev-dependencies]
rand = { version = "0.7" }
