version = "0.4.5 cdad051"
deployment = "deployment.toml"

[rust]
docker_image = "secbit/ckb-zkp-capsule:2021-05-30"

[[contracts]]
name = "universal_plonk_verifier"
template_type = "Rust"

[[contracts]]
name = "universal_groth16_verifier"
template_type = "Rust"

[[contracts]]
name = "mini_bulletproofs_verifier"
template_type = "Rust"

[[contracts]]
name = "mini_clinkv2_kzg10_verifier"
template_type = "Rust"

[[contracts]]
name = "mini_clinkv2_ipa_verifier"
template_type = "Rust"

[[contracts]]
name = "universal_spartan_nizk_verifier"
template_type = "Rust"

[[contracts]]
name = "universal_spartan_snark_verifier"
template_type = "Rust"

[[contracts]]
name = "universal_marlin_verifier"
template_type = "Rust"

[[contracts]]
name = "mini_libra_zk_linear_gkr_verifier"
template_type = "Rust"

[[contracts]]
name = "mini_hyrax_zk_linear_gkr_verifier"
template_type = "Rust"
