name: CI
# Refs:
# https://github.com/actix/actix/blob/master/.github/workflows/linux.yml
# https://github.com/starship/starship/blob/master/.github/workflows/workflow.yml

on:
  push:
    branches: [master, ci-amend]
  pull_request:
    branches: [master]

jobs:
  test_ckb-zkp:
    strategy:
      fail-fast: false
      matrix:
        version:
          - stable
        os:
          - ubuntu-latest
          - macos-latest
        include:
          - os: ubuntu-latest
            target: x86_64-unknown-linux-gnu
          - os: macos-latest
            target: x86_64-apple-darwin

    name: ${{ matrix.os }} - ${{ matrix.version }}-${{ matrix.target }}
    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v2

      - name: Setup Rust ${{ matrix.version }}
        uses: actions-rs/toolchain@v1
        with:
          toolchain: ${{ matrix.version }}
          profile: minimal
          override: true
          target: ${{ matrix.target }}

      - name: Generate Cargo.lock
        uses: actions-rs/cargo@v1
        with:
          command: generate-lockfile

      - name: Cache cargo dirs
        uses: actions/cache@v2
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            ~/.cargo/bin
          key: ${{ matrix.version }}-${{ matrix.target }}-cargo-trimmed-${{ hashFiles('**/Cargo.lock') }}
          restore-keys: |
            ${{ matrix.version }}-${{ matrix.target }}-cargo-trimmed-

      # - name: Cache cargo build
      #   uses: actions/cache@v2
      #   with:
      #     path: target
      #     key: ${{ matrix.version }}-${{ matrix.target }}-cargo-build-trimmed-${{ hashFiles('**/Cargo.lock') }}

      # - name: Check build
      #   uses: actions-rs/cargo@v1
      #   with:
      #     command: check
      #     args: --workspace --exclude=tests

      - name: All tests
        uses: actions-rs/cargo@v1
        # timeout-minutes: 120
        with:
          command: test
          args: --release --workspace --all-features --exclude=tests --no-fail-fast

      - name: Clear the cargo caches
        run: |
          which cargo-cache || cargo install cargo-cache --no-default-features --features ci-autoclean
          cargo-cache
